# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
  batch: true
  branches:
    include:   
    - master
  paths:
    include:
    - /createRemoteBackend/

stages:
- stage: Build
  jobs:
  - job: Build
    
    pool:
      vmImage: 'ubuntu-latest'

    steps:  
     
    - task: CopyFiles@2
      inputs:
        SourceFolder: 
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - job: Deploy
    
    pool:
      vmImage: 'ubuntu-latest'

    steps:  

    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    
    - task: TerraformCLI@0
      inputs:
        command: 'init'

    - task: TerraformCLI@0
      inputs:
        command: 'apply'
        environmentServiceName: 'Visual Studio Ultimate with MSDN (9bb74e1d-fcb4-4f14-b8ef-f4fc2865a77a)'



