# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yamlc


trigger:
  batch: true
  branches:
    include:   
    - master
  paths:
    include:
    - /terraform/

stages:
- stage: Build
  jobs:
  - job: Build
    
    pool:
      vmImage: 'vs2017-win2016'

    steps:  
     
    - task: CopyFiles@2
      inputs:
        SourceFolder: 
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - job: Deploy
    
    pool:
      vmImage: 'vs2017-win2016'

    steps:  
    

    - checkout: self
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.DefaultWorkingDirectory)'

    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '0.12.25' 
    

    - task: TerraformTaskV1@0
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendServiceArm: 'Visual Studio Ultimate with MSDN (9bb74e1d-fcb4-4f14-b8ef-f4fc2865a77a)'
        backendAzureRmResourceGroupName: 'randstad-tfstate-rg'
        backendAzureRmStorageAccountName: 'randstadtf9iydj9nc'
        backendAzureRmContainerName: 'core-tfstate'
        backendAzureRmKey: 'aksdeploy.tfstate'